version: "3.0"
services:
  mmcls-env:
    image: qiangzibro/mmclassification:latest
    build:
        context: ./
        dockerfile: docker/Dockerfile
    volumes:
        - .:/workspace
    tty: true
    ports:
        - "11000:11000"
        - "220:22"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=11000 --no-browser --notebook-dir=/workspace --allow-root --NotebookApp.token=''"
